# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # branch to trigger pipeline
 
pool:
  name: 'Default'  # or your self-hosted agent with Tosca installed
 
steps:
- task: PowerShell@2
  displayName: 'Run Tosca Tests'
  inputs:
    targetType: 'inline'
    script: |
      # Path to Tosca CommandLine executable
      $ToscaCmdPath = "C:\Program Files (x86)\TRICENTIS\Tosca Testsuite\ToscaCommander\ToscaCommander.exe"
      
      # ExecutionList and Workspace
      $ExecutionList = "C:\Users\SESA817735\Documents\Tosca\Script.tcs"
      $Workspace = "C:\Tosca_Projects\Tosca_Workspaces\UNIFY_TestAutomation\UNIFY_TestAutomation.tws"
      
      # Result folder
      $ResultFolder = "C:\ToscaResults"
      
      # Run Tosca
      & $ToscaCmdPath /ExecutionList=$ExecutionList /ProjectPath=$Workspace /ResultFolder=$ResultFolder /LoginUser="Imran" /Password="Imran"
      
      # Check results
      if($LASTEXITCODE -ne 0) {
          Write-Error "Tosca Tests failed. Check results in $ResultFolder"
          exit 1
      }